package com.cineseekerr.bot.bot;

import com.cineseekerr.bot.bot.state.*;
import com.cineseekerr.bot.bot.telegram.TelegramMessenger;
import com.cineseekerr.bot.client.*;
import com.cineseekerr.bot.model.*;
import com.cineseekerr.bot.parser.ReleaseNameParser;
import org.springframework.stereotype.Component;
import org.telegram.telegrambots.meta.api.objects.replykeyboard.InlineKeyboardMarkup;
import org.telegram.telegrambots.meta.api.objects.replykeyboard.buttons.*;
import java.util.*;
import java.util.function.Consumer;
import static com.cineseekerr.bot.bot.MessageFormatter.*;

/** Telegram UI for Arr's manual-search cache. The bot never calls a download client or filesystem. */
@Component
public class ConversationHandler {
 private static final int MAX=5; private static final String ANY="any";
 private final TmdbClient tmdb; private final RadarrClient radarr; private final SonarrClient sonarr;
 private final ReleaseNameParser parser; private final TelegramMessenger messenger; private final ConversationStateStore store;
 private final Messages messages; private final MessageFormatter formatter;
 public ConversationHandler(TmdbClient tmdb, RadarrClient radarr, SonarrClient sonarr, ReleaseNameParser parser,
     TelegramMessenger messenger, ConversationStateStore store, Messages messages, MessageFormatter formatter) {
  this.tmdb=tmdb;this.radarr=radarr;this.sonarr=sonarr;this.parser=parser;this.messenger=messenger;this.store=store;this.messages=messages;this.formatter=formatter;
 }
 public void onTextMessage(long chat,String text) { try { String t=text==null?"":text.strip(); if(t.isEmpty())return;
  if(t.startsWith("/")){command(chat,t);return;} ConversationState s=store.find(chat).orElse(null);
  if(s!=null&&s.step()==ConversationStep.AWAITING_MANUAL_SEASON) manualSeason(chat,s,t); else if(s!=null&&s.step()==ConversationStep.AWAITING_MANUAL_EPISODE) manualEpisode(chat,s,t); else start(chat,t,tmdb.searchTitles(t),"search.none.query");
 } catch(ApiClientException e){ messenger.sendHtml(chat,messages.get("error.generic",esc(e.getMessage())),null); } }
 public void onCallback(long chat,int msg,String callback,String data) { messenger.answerCallback(callback); if(data==null)return; if(data.equals("cancel")){store.clear(chat);messenger.editHtml(chat,msg,messages.get("cancel.done"),null);return;}
  ConversationState s=store.find(chat).orElse(null); if(s==null){messenger.editHtml(chat,msg,messages.get("session.expired"),null);return;} String[] p=data.split(":",2);String a=p[0],v=p.length>1?p[1]:"";
  try { switch(a) { case "movie"->at(s,ConversationStep.AWAITING_MOVIE_CHOICE,()->title(chat,s,index(v,s.candidates().size()))); case "season"->at(s,ConversationStep.AWAITING_SEASON_CHOICE,()->season(chat,s,v)); case "episode"->at(s,ConversationStep.AWAITING_EPISODE_CHOICE,()->episode(chat,s,v)); case "audio"->at(s,ConversationStep.AWAITING_AUDIO,()->filter(chat,s,v,ReleaseFilters::byAudio,x->s.setAudioFilter(x),Language::valueOf,()->nextSubs(chat,s))); case "subs"->at(s,ConversationStep.AWAITING_SUBTITLES,()->filter(chat,s,v,ReleaseFilters::bySubtitle,x->s.setSubtitleFilter(x),Language::valueOf,()->nextQuality(chat,s))); case "quality"->at(s,ConversationStep.AWAITING_QUALITY,()->filter(chat,s,v,ReleaseFilters::byQuality,x->s.setQualityFilter(x),Resolution::valueOf,()->nextFormat(chat,s))); case "format"->at(s,ConversationStep.AWAITING_FORMAT,()->filter(chat,s,v,ReleaseFilters::byFormat,x->s.setFormatFilter(x),VideoCodec::valueOf,()->shortlist(chat,s))); case "release"->at(s,ConversationStep.AWAITING_RELEASE_CHOICE,()->grab(chat,s,index(v,s.shortlist().size()))); case "back"->{if(s.backAction()!=null)s.backAction().run();} default->{} }
  } catch(ApiClientException e){store.clear(chat);messenger.editHtml(chat,msg,messages.get("error.generic",esc(e.getMessage())),null);} }
 private void command(long c,String raw){String[] p=raw.split("\\s+",2);String cmd=p[0].toLowerCase().replaceAll("@.*$","");String q=p.length>1?p[1].strip():""; switch(cmd){
  case "/start","/help"->messenger.sendHtml(c,messages.get("help"),null); case "/annulla","/cancel"->{store.clear(c);messenger.sendHtml(c,messages.get("cancel.done"),null);} case "/cerca","/search"->query(c,q,()->start(c,q,tmdb.searchTitles(q),"search.none.query"),"usage.cerca"); case "/film","/movie"->query(c,q,()->start(c,q,tmdb.searchMovies(q),"search.none.movie"),"usage.film"); case "/serie","/tv"->query(c,q,()->start(c,q,tmdb.searchTv(q),"search.none.tv"),"usage.serie"); case "/stato","/status"->status(c); default->messenger.sendHtml(c,messages.get("command.unknown"),null);}}
 private void status(long c){messenger.sendHtml(c,formatter.statusText(radarr.queue(),sonarr.queue()),null);}
 private void query(long c,String q,Runnable r,String usage){if(q.isEmpty())messenger.sendHtml(c,messages.get(usage),null);else r.run();}
 private void start(long c,String q,List<TmdbTitle> list,String none){store.clear(c);List<TmdbTitle> xs=list.stream().limit(MAX).toList();if(xs.isEmpty()){messenger.sendHtml(c,messages.get(none,esc(q)),null);return;}List<InlineKeyboardRow> rows=new ArrayList<>();for(int i=0;i<xs.size();i++)rows.add(new InlineKeyboardRow(button(NUMBER_EMOJI[i]+" "+icon(xs.get(i))+" "+truncate(titleLabel(xs.get(i)),32),"movie:"+i)));rows.add(cancel());Integer id=messenger.sendHtml(c,formatter.candidatesText(xs),keyboard(rows));ConversationState s=new ConversationState();s.setCandidates(xs);s.setMessageId(id);store.save(c,s);}
 private void title(long c,ConversationState s,int i){if(i<0)return;s.setTitle(s.candidates().get(i));if(s.title().isTv())seasons(c,s);else {s.setArrId(radarr.ensureMovie(s.title().id()).id()); releases(c,s);}}
 private void seasons(long c,ConversationState s){List<TmdbSeason> xs=tmdb.seasons(s.title().id());if(xs.isEmpty()){store.clear(c);edit(c,s,messages.get("seasons.none",esc(titleLabel(s.title()))),null);return;}s.setSeasons(xs);List<InlineKeyboardRow> rows=new ArrayList<>();for(TmdbSeason x:xs)rows.add(new InlineKeyboardRow(button(messages.get("seasons.button",x.seasonNumber(),x.episodeCount()),"season:"+x.seasonNumber())));rows.add(new InlineKeyboardRow(button(messages.get("seasons.manual.button"),"season:manual")));rows.add(cancel());s.setStep(ConversationStep.AWAITING_SEASON_CHOICE);save(c,s,messages.get("seasons.prompt",esc(titleLabel(s.title()))),keyboard(rows));}
 private void season(long c,ConversationState s,String v){if(v.equals("manual")){s.setStep(ConversationStep.AWAITING_MANUAL_SEASON);save(c,s,messages.get("seasons.manual.prompt"),keyboard(List.of(cancel())));return;}Integer n=positive(v);if(n!=null){s.setSeason(n);episodes(c,s);}}
 private void manualSeason(long c,ConversationState s,String v){Integer n=positive(v);if(n==null){messenger.sendHtml(c,messages.get("seasons.manual.invalid"),null);return;}s.setSeason(n);episodes(c,s);}
 private void episodes(long c,ConversationState s){int n=s.seasons().stream().filter(x->x.seasonNumber()==s.season()).findFirst().map(TmdbSeason::episodeCount).orElse(0);List<InlineKeyboardRow> rows=new ArrayList<>();rows.add(new InlineKeyboardRow(button(messages.get("episode.all.button"),"episode:all")));if(n>1)for(int e=1;e<=Math.min(n,96);e+=8){List<InlineKeyboardButton> row=new ArrayList<>();for(int x=e;x<Math.min(e+8,n+1);x++)row.add(button(""+x,"episode:"+x));rows.add(new InlineKeyboardRow(row));}else rows.add(new InlineKeyboardRow(button(messages.get("episode.manual.button"),"episode:manual")));rows.add(cancel());s.setStep(ConversationStep.AWAITING_EPISODE_CHOICE);save(c,s,messages.get("episode.prompt",esc(titleLabel(s.title())+" — "+messages.get("recap.season",s.season()))),keyboard(rows));}
 private void episode(long c,ConversationState s,String v){if(v.equals("manual")){s.setStep(ConversationStep.AWAITING_MANUAL_EPISODE);save(c,s,messages.get("episode.manual.prompt"),keyboard(List.of(cancel())));return;}s.setEpisode(v.equals("all")?null:positive(v));if(!v.equals("all")&&s.episode()==null)return;s.setArrId(sonarr.ensureSeries(s.title().id()).id());releases(c,s);}
 private void manualEpisode(long c,ConversationState s,String v){Integer n=positive(v);if(n==null){messenger.sendHtml(c,messages.get("episode.manual.invalid"),null);return;}s.setEpisode(n);s.setArrId(sonarr.ensureSeries(s.title().id()).id());releases(c,s);}
 private void releases(long c,ConversationState s){edit(c,s,messages.get("search.searching",esc(titleLabel(s.title()))),null);List<ArrRelease> rs=s.title().isTv()?sonarr.manualSearch(s.arrId(),s.season(),s.episode()):radarr.manualSearch(s.arrId());List<SearchResult> results=rs.stream().filter(ArrRelease::isApproved).map(r->new SearchResult(r,parser.parse(r.title()))).toList();if(results.isEmpty()){store.clear(c);edit(c,s,messages.get("search.none.releases",esc(titleLabel(s.title()))),null);return;}s.setAllResults(results);s.setFiltered(results);nextAudio(c,s);}
 private <T> void filter(long c,ConversationState s,String raw,java.util.function.BiFunction<List<SearchResult>,T,List<SearchResult>> apply,Consumer<T> set,java.util.function.Function<String,T> parse,Runnable next){T x=raw.equals(ANY)?null:parse.apply(raw);set.accept(x);s.setFiltered(apply.apply(s.filtered(),x));next.run();}
 private void nextAudio(long c,ConversationState s){choose(c,s,"step.audio","audio",ReleaseFilters.audioBuckets(s.filtered()),x->nextSubs(c,s));} private void nextSubs(long c,ConversationState s){choose(c,s,"step.subtitles","subs",ReleaseFilters.subtitleBuckets(s.filtered()),x->nextQuality(c,s));} private void nextQuality(long c,ConversationState s){choose(c,s,"step.quality","quality",ReleaseFilters.qualityBuckets(s.filtered()),x->nextFormat(c,s));} private void nextFormat(long c,ConversationState s){choose(c,s,"step.format","format",ReleaseFilters.formatBuckets(s.filtered()),x->shortlist(c,s));}
 private <T> void choose(long c,ConversationState s,String key,String action,Map<T,Long> choices,Consumer<Void> next){if(choices.size()<=1){next.accept(null);return;}List<InlineKeyboardRow> rows=new ArrayList<>();rows.add(new InlineKeyboardRow(button(messages.get(action.equals("subs")?"option.subs.any":"option.any",s.filtered().size()),action+":"+ANY)));for(var e:choices.entrySet())rows.add(new InlineKeyboardRow(button(e.getKey()+" ("+e.getValue()+")",action+":"+callbackValue(e.getKey()))));rows.add(cancel());s.setStep(switch(action){case "audio"->ConversationStep.AWAITING_AUDIO;case "subs"->ConversationStep.AWAITING_SUBTITLES;case "quality"->ConversationStep.AWAITING_QUALITY;default->ConversationStep.AWAITING_FORMAT;});save(c,s,formatter.stepHeader(s)+messages.get(key),keyboard(rows));}
 private void shortlist(long c,ConversationState s){s.setShortlist(s.filtered().stream().sorted(Comparator.comparingInt(SearchResult::seeders).reversed()).limit(MAX).toList());List<InlineKeyboardRow> rows=new ArrayList<>();for(int i=0;i<s.shortlist().size();i++)rows.add(new InlineKeyboardRow(button(NUMBER_EMOJI[i],"release:"+i)));rows.add(cancel());s.setStep(ConversationStep.AWAITING_RELEASE_CHOICE);save(c,s,formatter.shortlistText(s),keyboard(rows));}
 private void grab(long c,ConversationState s,int i){if(i<0)return;ArrRelease r=s.shortlist().get(i).release();if(s.title().isTv())sonarr.grab(r);else radarr.grab(r);store.clear(c);edit(c,s,messages.get("download.sent.title")+"\n\n"+messages.get("download.sent.footer"),null);}
 private void at(ConversationState s,ConversationStep expected,Runnable r){if(s.step()==expected)r.run();} private int index(String x,int n){try{int i=Integer.parseInt(x);return i>=0&&i<n?i:-1;}catch(Exception e){return -1;}} private Integer positive(String x){try{int n=Integer.parseInt(x);return n>0?n:null;}catch(Exception e){return null;}}
 static String callbackValue(Object value){return value instanceof Enum<?> choice?choice.name():String.valueOf(value);}
 private InlineKeyboardButton button(String t,String d){return InlineKeyboardButton.builder().text(t).callbackData(d).build();} private InlineKeyboardRow cancel(){return new InlineKeyboardRow(button(messages.get("cancel.button"),"cancel"));} private InlineKeyboardMarkup keyboard(List<InlineKeyboardRow> r){return new InlineKeyboardMarkup(r);} private void save(long c,ConversationState s,String t,InlineKeyboardMarkup k){store.save(c,s);edit(c,s,t,k);} private void edit(long c,ConversationState s,String t,InlineKeyboardMarkup k){messenger.editHtml(c,s.messageId(),t,k);}
}
